### ISSUE TITLE
Reason behind working on this project

### ISSUE THREAD

**Issue by nikhilrayaprolu** [timestocome/Test-stock-prediction-algorithms#3]
I really liked the way you are working on this project, by not just using the Deep Learning models but also adding traditional technical analysis to it.
Can I know why you are working on this? An open-Source Consultation, or a Research Project, an assignment, or just out of interest?

**Comment by timestocome** [comment]
The main reason is to learn all there is about time series projections, anomaly detection etc. Stocks just happen to be an interesting time series.
