### ISSUE TITLE
Wanna contribute on this project 

### ISSUE THREAD

**Issue by grrrrreee** [timestocome/Test-stock-prediction-algorithms#5]
Can I contribute on this project by adding some reading list and useful website???
And later also suggest some ways to predict stock with genetic algorithm?

**Comment by timestocome** [comment]
Thanks, this is just a toy project for me to learn about different methods
of predicting time series, once I finish the RL book I'm working through.
I'll be trying GA too. There just hasn't been much free time lately

You can fork it, there are several forks already and update the reading
list and add your code.

Please send a link, I'm dying to get into GA and I'd love to see what you
do.

Linda

Linda MacPhee-Cobb
https://github.com/timestocome

**Comment by grrrrreee** [comment]
Thank you so much ma'am
gonna pull the request after I solve that problem with GA 
thnx again!!

**Comment by ebredy** [comment]
I would love to see what you do with the ga algorithm. Can I get the forked git link as well? Thanks.

**Comment by timestocome** [comment]
I think the GA is probably going to do better than the RL, we'll see. I'm still working out how to set it up. If I have them buy/sell any amount it creates too many states for the limited data available. So I'm trying to find the sweet spot between constraints and the amount of data. I'll be working through the rest of the MCDP book and posting those while I think about it.

Yes, just click on the fork link on any project and GitHub should set it up

Send me a link to yours too, I'd love to see what you do
