### ISSUE TITLE
jupyter / ipython notebook  - a new test with PredictMarketWithBayesTheorem

### ISSUE THREAD

**Issue by ag88** [timestocome/Test-stock-prediction-algorithms#6]
any plans to use the jupyter notebook?
https://jupyter.org/
graphs e.g. pyplot etc are somewhat easier with that, but that it would probably consume significantly more memory and resources

i did a new test of PredictMarketWithBayesTheorem in my repository
[PredictMarketWithBayesTheorem.ipynb](https://github.com/ag88/Test-stock-prediction-algorithms/blob/master/Curves%2C%20Markov%20and%20Bayes/PredictMarketWithBayesTheorem.ipynb)

the main things i changed are
normally log returns is computed as log(today's price) - log(yesterday's price) = log ( today's price / yesterday's price ). hence this formula is used instead
and for the categories i used a histogram to define them, scroll below for the histogram

this time round there is a difference, what is most interesting is the HL and HG predictions

**Comment by timestocome** [comment]
I've been using Jupyter Notebooks for newer projects I'm working on. I've been buried and watching the world implode so I haven't put much up here. Older stuff won't be converted, newer stuff will likely be in Jupyter Notebooks

**Comment by ag88** [comment]
thanks, this is just a suggestion, no worries and no hurries ;)
